[package]
name = "ring"
version = "0.1.0"
edition = "2021"

[dependencies]
k256="0.13"
methods = { path = "../methods" }
rand = "0.8"
risc0-zkvm = { version = "1.0.5" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"