[package]
name = "birthday"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.0.5", default-features = false, features = [ "std" ] }
birthday-core = { path = "../../core" }